name: GodMode
main: LDX\GodMode\Main
version: 2.2
api: [1.0.0,1.1.0,1.2.0]
load: POSTWORLD
author: LDX
website: https://github.com/LDX-MCPE/GodMode
commands:
 god:
  description: "Toggles God mode for you or the specified player"
  usage: "/god [player]"
  permission: godmode.toggle
permissions:
 godmode.toggle:
  description: "Allows the player to toggle God mode"
  default: op
  children:
   godmode.toggle.self:
    description: "Allows the player to toggle God mode for themselves"
    default: op
   godmode.toggle.others:
    description: "Allows the player to toggle God mode for others"
    default: op
